### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by mao3329** [mao3329/protospace-32525#1]
＃URL
https://protospace-32525.herokuapp.com/

**Comment by tomoko-yokoyama** [comment]
竹部さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

プロトタイプ詳細ページにおいて、プロトタイプ投稿時に登録した「プロトタイプの名称」が表示されませんでした。
（どのプロトタイプも「プロトタイプのタイトル」と名称が表示されてしまっております。）

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tomoko-yokoyama** [comment]
竹部さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
